feat: Auto-publish on commit to master
ratehub/code-style pull request #22
Opened 2022-07-25 19:24 UTC by ryuuji3

Closes #21

2022-07-25 19:27 UTC, Voziv commented on .github/workflows/release.yml
> +    paths:
```suggestion
    paths:
     - 'javascript/**'
     - 'css/**'
     - 'react/**'
```

2022-07-25 19:41 UTC, chris-skoblenick approved these changes

2022-07-25 19:42 UTC, morey-tech requested changes
I'm not confident that this will work. Semantic-release compares the commit from the last release tag to the current commit. If there is a `feat` add on one function, each package may get a minor version bump. The `semantic-release-monorepo` plugin is what added only using commits that changed files in the package to influence the version number.

2022-07-26 18:18 UTC, morey-tech approved these changes
LGTM! 

Note that I added `ratehub-machine` to the repo with Write permissions and added it to the "Allow specified actors to bypass required pull requests" list on the branch protection rules. This way it has the access needed to push the release commit.

2022-07-26 21:03 UTC, merged